#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Check for unstaged changes..."
if [ -n "$(git status --porcelain)" ]; then
  echo "Push blocked: Working tree is not clean."
  git status --short
  exit 1
fi

echo "Running lint..."
npm run lint

echo "Running type check..."
npx tsc --noEmit

echo "Building project..."
npm run build
